### ISSUE TITLE
Request: method to download multiple files at once and .zip them all together

### ISSUE THREAD

**Issue by timhussey** [kamilZ/B2Backblaze#1]
will there be a function to pass an array of filenames
and have it zip them all together and then save as a file so the user can downoad it?

**Comment by kamilZ** [comment]
Done. Added getAllZip(....) method. 
Please, check if works @timhussey. Pull requests are wellcome :)

**Comment by timhussey** [comment]
awesome!
Right now i'm just waiting for my beta account to be approved (tim@pixifi.com)
(any chance you can help me get approved sooner?)

once it is, then i'll get in there and start building all of this!!!
THANKS for adding that in!!!
Can't wait to try this all!!
-Tim

**Comment by kamilZ** [comment]
Ok. I can't help you with beta account thing, sorry.
