### ISSUE TITLE
Upload dont work

### ISSUE THREAD

**Issue by n0v3xx** [kamilZ/B2Backblaze#3]
Hi,

i tested the lib and all my file uploads are 44kb empty files after upload.
I tested it with a 25mb rar file and a jpeg image. All are after upload empty small files.
Whats wrong?

**Comment by kamilZ** [comment]
@n0v3xx Are you still struggling with this?

**Comment by n0v3xx** [comment]
The insert Method upload only 44kb files. And the insertLage Method upload nothing.
Yes still not work for me

**Comment by nibinpaul** [comment]
Pass file variable through file_get_contents() function may solve your problem.
$client->insert($bucketId, file_get_contents($file), $fileName);
